# Generated by Django 5.2.1 on 2025-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('project_manager', 'Project Manager')], default='regular_user', max_length=32, verbose_name='Роль'),
        ),
    ]
