# Generated by Django 5.2.1 on 2025-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_comment_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=8192),
            preserve_default=False,
        ),
    ]
